<Project>

  <Sdk Name="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Andrey Talanin</Authors>
    <Description>A set of utilities for creating enumerable objects using the yield operator.</Description>
    <RepositoryUrl>https://github.com/AndreyTalanin0x00/AndreyTalanin0x00.YieldHelpers.git</RepositoryUrl>
    <Version>0.1.0-rc1</Version>
  </PropertyGroup>

</Project>
